server:
  port: 5055

spring:
    datasource:
      test1:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/test1?useUnicode=true&characterEncoding=utf-8&useSSL=false
          type: com.alibaba.druid.pool.DruidDataSource
          username: root
          password: 123456
          # 下面为连接池的补充设置，应用到上面所有数据源中# 初始化大小，最小，最大
          initialSize: 5
          minIdle: 5
          maxActive: 20
          # 配置获取连接等待超时的时间
          maxWait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 300000
          #在每次空闲连接回收器线程(如果有)运行时检查的连接数量，最好和maxActive一致
          numTestsPerEvictionRun: 20
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall,log4j
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      test2:
          driver-class-name: com.mysql.jdbc.Driver
          url: jdbc:mysql://127.0.0.1:3306/test2?useUnicode=true&characterEncoding=utf-8&useSSL=false
          type: com.alibaba.druid.pool.DruidDataSource
          username: root
          password: 123456
          # 下面为连接池的补充设置，应用到上面所有数据源中# 初始化大小，最小，最大
          initialSize: 5
          minIdle: 5
          maxActive: 20
          # 配置获取连接等待超时的时间
          maxWait: 60000
          # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
          timeBetweenEvictionRunsMillis: 60000
          # 配置一个连接在池中最小生存的时间，单位是毫秒
          minEvictableIdleTimeMillis: 300000
          #在每次空闲连接回收器线程(如果有)运行时检查的连接数量，最好和maxActive一致
          numTestsPerEvictionRun: 20
          validationQuery: SELECT 1 FROM DUAL
          testWhileIdle: true
          testOnBorrow: false
          testOnReturn: false
          # 打开PSCache，并且指定每个连接上PSCache的大小
          poolPreparedStatements: true
          maxPoolPreparedStatementPerConnectionSize: 20
          # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
          filters: stat,wall,log4j
          # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
          connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

mybatis:
    typeAliasesPackage: com.wangxin.spring.boot.demo.domain
    mapperLocations: classpath:com/wangxin/mapper/*.xml
    pagehelper:
      dialect: mysql
      #默认为false, 为true时，会将RowBounds第一个参数offset当成pageNum页码使用, 和startPage中的pageNum效果一样
      offsetAsPageNum: true
      #默认为false, 为true时，使用RowBounds分页会进行count查询
      rowBoundsWithCount: true
      #为true时，如果pageSize=0或者RowBounds.limit = 0就会查询出全部的结果
      pageSizeZero: true
      #启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages会查询最后一页;禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
      reasonable: true
      #增加了一个`params`参数来配置参数映射，用于从Map或ServletRequest中取值, 可以配置pageNum,pageSize,count,pageSizeZero,reasonable,orderBy,不配置映射的用默认值
      params: pageNum=start;pageSize=limit;
      #支持通过Mapper接口参数来传递分页参数
      supportMethodsArguments: true
      #always总是返回PageInfo类型,check检查返回类型是否为PageInfo,none返回Page
      returnPageInfo: true